/** Shared form control class names — styles defined in index.css */
export const formInput = 'form-control form-input'
export const formSelect = 'form-control form-select'
export const formSelectFixed = 'form-control form-select form-select-fixed'
export const formSelectWide = 'form-control form-select form-select-wide'
export const formSelectMedium = 'form-control form-select form-select-medium'
export const formSelectWrap = 'form-select-wrap'
export const formSelectDropdown =
  'absolute left-0 top-full z-[1100] mt-1 min-w-full rounded-lg border border-border bg-surface shadow-xl'
export const formSelectDropdownSearch = 'border-b border-border p-2'
export const formSelectDropdownList = 'max-h-56 overflow-y-auto py-1'
export const formSelectDropdownItem =
  'flex w-full cursor-pointer items-center px-3 py-1.5 text-left text-xs text-text-muted hover:bg-navy-950/60'
export const formSelectDropdownItemSelected = 'bg-accent/10 font-medium text-white'
export const formSelectDropdownEmpty = 'px-3 py-3 text-center text-xs text-text-muted'
export const formToolbar = 'form-toolbar flex shrink-0 flex-nowrap items-center gap-3'
export const formDate = 'form-control form-date'
export const formCheckbox = 'form-checkbox'
export const formCheckLabel = 'form-check-label'
export const formDateGroup = 'form-date-group'
export const formLabel = 'form-label'

export const btnPrimary = 'btn btn-primary'
export const btnSecondary = 'btn btn-secondary'
export const btn = 'btn'
export const btnGhost = 'btn btn-ghost'
export const btnIcon = 'btn btn-icon'
export const btnSegmentGroup = 'btn-segment-group'
export const btnSegment = 'btn-segment'
export const btnSegmentActive = 'btn-segment-active'
