/** Shared form control class names — styles defined in index.css */
export const formInput = 'form-control form-input'
export const formSelect = 'form-control form-select'
export const formSelectFixed = 'form-control form-select form-select-fixed'
export const formSelectWide = 'form-control form-select form-select-wide'
export const formSelectMedium = 'form-control form-select form-select-medium'
export const formSelectWrap = 'form-select-wrap'
export const formToolbar = 'form-toolbar flex shrink-0 flex-nowrap items-center gap-3'
export const formDate = 'form-control form-date'
export const formCheckbox = 'form-checkbox'
export const formCheckLabel = 'form-check-label'
export const formDateGroup = 'form-date-group'
export const formLabel = 'form-label'

export const btnPrimary = 'btn btn-primary'
export const btnSecondary = 'btn btn-secondary'
export const btn = 'btn'
export const btnGhost = 'btn btn-ghost'
export const btnIcon = 'btn btn-icon'
export const btnSegmentGroup = 'btn-segment-group'
export const btnSegment = 'btn-segment'
export const btnSegmentActive = 'btn-segment-active'
